FROM @IMAGE_BUILDROOT@:@ARCH@

ENV PS1="[\u@\h \W]\$ "
ENV TMPDIR="/tmp"

USER root

RUN \
 apt-get -y update;\
 apt-get -y install sh @PKGLIST@;\
 apt-get -y clean;

VOLUME ["/.in", "/.out", "/.host"]
USER @USER@

CMD /bin/sh
