#!/bin/sh -efu

. shell-error
. shell-args
. shell-signal

path="$(readlink -ev "$0")"
path="${path%/*}"

. "$path/docker-hsh-functions"

target_arch="$def_arch"

show_help()
{
	cat <<EOF
$PROG - TODO

EOF
	exit
}

docker_id=
workdir=
exit_handler()
{
	[ -z "$docker_id" ] || docker rm -f -v "$docker_id" ||:
	[ -z "$workdir" ] || rm -rf -- "$workdir"
}

docker_exec_root()
{
	docker exec -u root -i "$docker_id" "$@"
}

docker_exec_user()
{
	docker exec -i "$docker_id" "$@"
}

create_volumes()
{
	rm -rf -- "$workdir"/container
	mkdir -p \
		"$workdir"/container/in \
		"$workdir"/container/out/rpms \
		"$workdir"/container/out/srpms \
		"$workdir"/container/host
}

filter_spec_buildreq()
{
	tr -s '[:blank:],' ' ' |
		while read REPLY; do
			set -- $REPLY
			while [ -n "${1-}" ]; do
				case "${2-}" in
					=|["<>"]|["<>"]=)
						[ -z "${1##*%*}" -o -z "${3##*%*}" ] ||
							printf %s\\n "$1 $2 $3"
						shift 2
						;;
					*)
						[ -z "${1##*%*}" ] ||
							printf %s\\n "$1"
						;;
				esac
				if ! shift; then
					fatal "Invalid build dependencies: $REPLY"
				fi
			done
		done
}

calc_check_build_deps()
{
	build_deps="$(filter_spec_buildreq |LC_ALL=C grep -v '^rpmlib(' |LC_ALL=C tr -d [[:blank:]])"
	if [ -z "$build_deps" ]; then
		verbose "$pkgname: build dependencies not found"
		return
	fi
	verbose "$pkgname: calculated build dependencies: $(printf %s "$build_deps" |tr -s '[:space:]' ' ')"

	local bad_deps
	if bad_deps="$(printf %s "$build_deps" |LC_ALL=C grep -v '^[[:alnum:]_/]')"; then
		fatal "$pkgname: invalid build dependencies: $(printf %s "$bad_deps" |tr -s '[:space:]' ' ')"
	fi

	printf '%s\n' $build_deps
}


TEMP=`getopt -n $PROG -o f,$getopt_common_opts -l arch:,no-cache,repo-bin:,repo-src:,$getopt_common_longopts -- "$@"` ||
	show_usage
eval set -- "$TEMP"

while :; do
	case "$1" in
		--arch) shift
			[ -n "$1" ] ||
				fatal "arch cannot be empty"
			target_arch="$1"
			;;
		--repo-bin) shift
			repo_bin="$1"
			;;
		--repo-src) shift
			repo_src="$1"
			;;
		--no-cache)
			no_cache=--no-cache
			;;
		--) shift; break
			;;
		*) parse_common_option "$1"
			;;
	esac
	shift
done

[ "$#" = 1 ] ||
	fatal "More arguments required"

pkg="$(readlink -ev "$1")"
pkgname="${pkg##*/}"
image_tag="$target_arch"

set_cleanup_handler exit_handler
workdir="$(mktemp -dt "$PROG.XXXXXXXXX")"

create_volumes

cd "$workdir"

create_entry_root_header container/host/init
cat >>container/host/init <<EOF
set -efu
while :; do sleep 1; done
EOF

verbose "Running container..."
docker_id=$(docker run -d \
	--cap-add ALL \
	-u root \
	-v "$workdir/container/in:/.in" \
	-v "$workdir/container/host:/.host" \
	"$image_buildroot:$image_tag" \
	/.host/init)

verbose "Coping source package..."
cp $verbose -f -- "$pkg" container/in/

create_entry_header container/host/entry
cat >>container/host/entry <<EOF
rpmquery -p "/.in/$pkgname" --qf='[%{FILENAMES}\t%{FILEDIGESTS}\n]\n'
EOF
docker_exec_root /.host/entry >"$workdir/rpm-digests" &&
	verbose "$pkgname: fetched files digests." ||
	fatal "$pkgname: failed to fetch files digests from source package."

pkgdigest="$(LC_ALL=C sort -u "$workdir/rpm-digests" |sha1sum |cut -d\  -f1)"

if [ -n "$no_cache" ] && is_docker_image_exists "$pkgdigest:$image_tag"; then
	docker rmi -f "$pkgdigest:$image_tag" ||
		fatal "Unable to remove previous image: $pkgdigest:$image_tag"
fi

if ! is_docker_image_exists "$pkgdigest:$image_tag"; then
	verbose "Extracting specfile..."
	cp $verbose -f -- "$helperdir/rpm-extract-specfile" container/host/

	create_entry_header container/host/entry
	cat >>container/host/entry <<-EOF
	/.host/rpm-extract-specfile "/.in/$pkgname"
	EOF
	docker_exec_root /.host/entry >"$workdir/specfile" &&
		verbose "$pkgname: fetched specfile." ||
		fatal "$pkgname: failed to fetch specfile."

	:>"$workdir/builddeps"

	verbose "Installing buildrequires(pre)..."
	sed -e '/^buildrequires(pre):[[:space:]]*/I!d;s///' "$workdir/specfile" |
		calc_check_build_deps >> "$workdir/builddeps"

	builddeps="$(LC_ALL=C tr -s '[:space:]' ' ' < "$workdir/builddeps")"
	if [ -n "$builddeps" ]; then
		create_entry_header container/host/entry
		cat >>container/host/entry <<-EOF
		apt-get -y install $builddeps
		EOF
		docker_exec_root /.host/entry
	fi

	verbose "Installing buildrequires..."
	cp $verbose -f -- "$workdir/specfile" container/in/

	create_entry_header container/host/entry
	cat >>container/host/entry <<-EOF
	rpmbuild -bE --target="$target_arch" -- /.in/specfile
	EOF
	docker_exec_root /.host/entry >"$workdir/specfile" &&
		verbose "$pkgname: parse specfile" ||
		fatal "$pkgname: failed to fetch specfile."

	"$helperdir/hsh-buildreq-filter" < "$workdir/specfile" |
		calc_check_build_deps >>"$workdir/builddeps"

	expand_vars_pkglist="$(LC_ALL=C tr -s '[:space:]' ' ' < "$workdir/builddeps")"
	expand_vars <"$helperdir/Dockerfile.build" >"$workdir/Dockerfile"

	docker build $no_cache \
		--force-rm --rm \
		-t "$pkgdigest:$target_arch" \
		-f "$workdir/Dockerfile" .
fi

docker rm -f -v "$docker_id"
docker_id=

create_volumes

verbose "Installing source package..."
cp $verbose -f -- "$pkg" container/in/

verbose "Building package..."
create_entry_header container/host/entry
cat >>container/host/entry <<EOF
set -eu +f

rpm -i "/.in/$pkgname"
cd \`rpm --eval %_specdir\`

${verbose:+set -x}

exec >&2 time rpmbuild -ba \\
  --target="$target_arch" \\
  --define '_rpmdir /.out/bin' \\
  --define '_srcrpmdir /.out/src' \\
  *.spec
EOF

docker run -i \
	--net=none \
	--cap-add ALL \
	-u root \
	-v "$workdir/container/in:/.in" \
	-v "$workdir/container/out:/.out" \
	-v "$workdir/container/host:/.host" \
	--rm \
	"$pkgdigest:$target_arch" \
	/.host/entry

mkdir -p -- "$repo_bin" "$repo_src"

find container/out/bin -type f -name '*.rpm'     -exec cp $verbose -ft "$repo_bin" '{}' \+
find container/out/src -type f -name '*.src.rpm' -exec cp $verbose -ft "$repo_src" '{}' \+
